name: Build, Test & Deploy

defaults:
  run:
    working-directory: frontend

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-test:
    timeout-minutes: 60
    name: "Build & Test"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm install -g pnpm && pnpm install

    - name: Build the frontend
      run: pnpm build

    - name: Upload frontend artifact
      uses: actions/upload-artifact@v3
      with:
        name: frontend-artifact
        path: frontend/dist/**

    - name: Install Playwright browsers
      run: npx playwright install

    - name: Run Playwright tests
      run: pnpm exec playwright test

    - name: Upload Playwright report
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: frontend/playwright-report/**

  web-deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-artifact
          path: build

      - name: 📂 Sync files to Combell
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir        : build/
          server-dir: astro-build/
